onlineclasses/urls.py
from django.urls import path
from onlineclasses.views import home,verifypayment,my_courses
from onlineclasses.views.courses import course_page
from onlineclasses.views.contact_us import contact_us
from onlineclasses.views.explore_courses import explore_courses
from onlineclasses.views import SignupView,LoginView,signout,checkout
from onlineclasses.views.auth import(
                CustomPasswordResetView,
                CustomPasswordResetDoneView,
                CustomPasswordResetConfirmView,
                CustomPasswordResetCompleteView
)

urlpatterns = [
    path("", home, name='home'),
    path("logout", signout, name='logout'),
    path("my_courses", my_courses, name='my_courses'),
    path("signup", SignupView.as_view(), name='Signup'),
    path("login", LoginView.as_view(), name='login'),
    path("contact_us/", contact_us, name='contact_us'), 
    path("explore_courses", explore_courses, name='explore_courses'),
    path("courses/<str:slug>", course_page, name='course_page'),
    path("checkout/<str:slug>", checkout, name='checkout_page'),
    path("verify_payment", verifypayment, name='verify_payment'),
    
    path("reset_password/",CustomPasswordResetView.as_view(template_name = "courses/password_reset.html"),
         name='password_reset'),
    path("reset_password_sent/",CustomPasswordResetDoneView.as_view(template_name = "courses/password_reset_sent.html"), 
         name='password_reset_done'),
    path("reset/<uidb64>/<token>/",CustomPasswordResetConfirmView.as_view(template_name = "courses/password_reset_form.html"),
         name='password_reset_confirm'),
    path("reset_password_complete/",CustomPasswordResetCompleteView.as_view(template_name = "courses/password_reset_complete.html"),
         name='password_reset_complete'),
]

onlineclasses/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    title = models.CharField(max_length=100,default='Default Title')

    def __str__(self):
        return self.title
class Course(models.Model):
    title = models.CharField(max_length=100,null=False)
    slug = models.CharField(max_length=100,null=False,unique=True)
    description = models.TextField(max_length=500,null=True)
    duration = models.PositiveIntegerField(help_text="Duration:")
    price = models.IntegerField(null=False)
    discount = models.PositiveIntegerField(null=False, default=0)
    is_published = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    length = models.PositiveIntegerField(null=False)
    
    def __str__(self):
        return self.title

class Lesson(models.Model):
    title = models.CharField(max_length=100)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    order = models.PositiveIntegerField()
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.title

class Class(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    starting_time = models.DateTimeField()
    ending_time = models.DateTimeField()
    
    def __str__(self):
        return self.title
    

class Enrollment(models.Model):
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    enrollment_date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.title

class Usercourse(models.Model):
    user = models.ForeignKey(User,null=False,on_delete=models.CASCADE)
    course = models.ForeignKey(Course,null=False,on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'{self.user.username} {self.course.title}'
    
class Payment(models.Model):
    order_id = models.CharField(max_length=50,null=True)
    payment_id = models.CharField(max_length=50,null=True)
    user_course = models.ForeignKey(Usercourse,null=True,blank=True, on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    course = models.ForeignKey(Course,on_delete=models.CASCADE)
    payment_date = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=False)
    
class Recording(models.Model):
    class_instance = models.ForeignKey(Class, on_delete=models.CASCADE)
   # video_file = models.FileField(upload_to='recordings/')
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.title

onlineclasses/forms/login_form.py
from django.contrib.auth.forms import AuthenticationForm
from django import forms
from django.contrib.auth import authenticate,login
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=25, required=True,label='username')

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        user = None

        try:
            user = User.objects.get(username=username)
            result = authenticate(username=user.username, password=password)
            if result is not None:
                return result
            else:
                raise forms.ValidationError("Invalid credentials")
        except User.DoesNotExist:
            raise forms.ValidationError("Invalid Credentials")

onlineclasses/forms/registration_forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.forms import ValidationError 

class RegistrationForm(UserCreationForm):
    first_name = forms.CharField(max_length=20, required=True)
    last_name = forms.CharField(max_length=20, required=True)
    email = forms.EmailField(max_length=30, required=True)
    
    class Meta:
        model = User
        fields = ["first_name", "last_name","username","email", "password1", "password2"]
        
    def clean_email(self):
        email = self.cleaned_data["email"]
        user = None
        try:
            user = User.objects.get(email=email)
        except:
            return email
        if (user is not None):
            raise ValidationError("Email already in use") 

onlineclasses/views/checkout.py
from time import time
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.contrib.auth import login
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render,redirect
from onlineclasses.models import Course,Payment,Usercourse
from myproject.settings import *
import razorpay
client = razorpay.Client(auth=(KEY_ID, KEY_SECRET))

def checkout(request,slug):
    course = Course.objects.get(slug=slug)
    if(request.user.is_authenticated is False):
        return redirect('login')
    user = request.user
    action = request.GET.get('action')
    order = None
    payment = None
    error = None
    if action == 'create_payment':
        
        try:
            user_course = Usercourse.objects.get(user=user,course=course)
            error = "You are already enrolled in this course"
        except:
            pass
        if error is None:
            discounted_price = course.price * (1 - course.discount * 0.01)
            amount = max(int(discounted_price * 100), 1)

            currency ="INR"
            #receipt =
            notes ={
                'email': user.email,
                'name': f'{user.first_name} {user.last_name}'
            } 
            receipt = f"RKMVCC-{int(time())}"
            order = client.order.create(
                {
                'receipt': receipt,
                'notes': notes,
                'amount': amount,
                'currency':currency
                }
            )
            
            payment = Payment()
            payment.user = user
            payment.course = course
            payment.order_id = order['id']
            payment.save()
    context = {
        'course':course,
        'order':order,
        'payment':payment,
        'user':user,
        'error':error
    }
    return render(request,template_name= "courses/checkout.html",context=context)

@csrf_exempt
def verifypayment(request):
    if request.method == 'POST':
        print(request.POST)
        data = request.POST
        context = {}
        try:
            client.utility.verify_payment_signature(data)
            razorpay_order_id = data['razorpay_order_id']
            razorpay_payment_id = data['razorpay_payment_id']
            
            
            payment = Payment.objects.get(order_id = razorpay_order_id)
            payment.payment_id = razorpay_payment_id
            payment.status = True
            
            userCourse = Usercourse(user = payment.user,course = payment.course)
            userCourse.save()
            
            payment.user_course = userCourse
            payment.save()
            login(request,payment.user)
            
            return redirect('my_courses')
        except:
            return HttpResponse("Invalid Payment details")

onlineclasses/views/contact_us.py
from django.shortcuts import render

def contact_us(request):
    return render(request, template_name='courses/contact_us.html')

onlineclasses/views/courses.py
from django.shortcuts import render,redirect
from django.shortcuts import HttpResponse
from onlineclasses.models import Course,Usercourse
from django.contrib.auth.decorators import login_required

def course_page(request,slug):
    course = Course.objects.get(slug=slug)
    context = {
        "course": course
    }
    return render(request,template_name= "courses/course_page.html",context=context)
@login_required(login_url="login")
def my_courses(request):
    user = request.user
    user_course = Usercourse.objects.filter(user = user)
    context ={
        'user_course': user_course
    }
    return render(request, template_name="courses/my_courses.html",context=context)

onlineclasses/views/explore_courses.py
from django.shortcuts import render
from onlineclasses.models import Course
def explore_courses(request):
    courses = Course.objects.all()
    print(courses)
    return render(request, template_name='courses/explore_courses.html',context={"courses": courses})

onlineclasses/views/homepage.py
from django.shortcuts import render
from onlineclasses.models import Course

def home(request):
    courses = Course.objects.all()
    print(courses)
    return render(request, template_name='courses/home.html',context={"courses": courses}) 

onlineclasses/templates/courses/base.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title>
    {% block title %}
    {% endblock %}
  </title>

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
    integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

  <title>Hello world!</title>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">Navbar</a>

    <style>
      .navbar {
      font-size: 34px;
      padding: 10px;
      color: white; 
    }
      .btn-login,
      .btn-logout,
      .btn-signup,
      .btn-contact_us {
        font-size: 20px;
        background-color: #4caf50;
        color: #FFFFFF;
        border: none;
        padding: 10px 20px;
        cursor: pointer;
        border-radius: 3px;
        margin-right: 10px;
      }
      .btn-home {
      font-size: 30px; /* Increase the font size as desired */
      padding: 10px 20px; /* Adjust padding values as needed */
    }
    </style>

    <ul class="navbar-nav text-left"></ul>
    <li class="nav-item">
      <a class="btn-home" href="/">Home</a>
    </li>
    <!-- left-->
    <li class="nav-item">
      <a class="btn-contact_us" href="/contact_us">Contact us</a>
    </li>

    <ul class="navbar-nav ml-auto">
      {% if request.user.is_authenticated %}
      <li class="nav-item">
        <a class="btn-logout" href="/my_courses">My courses</a>
      </li>
      <li class="nav-item">
        <a class="btn-logout" href="/logout">logout</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="btn-login" href="/login">login</a>
      </li>
      <li class="nav-item">
        <a class="btn-signup" href="/signup">signup</a>
      </li>
      {% endif %}
    </ul>

  </nav>

  {% block content %}

  {% endblock %}

  <!-- Optional JavaScript; choose one of the two! -->

  <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
    crossorigin="anonymous"></script>

  <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
</body>

</html>

onlineclasses/templates/courses/checkout.html
{% extends 'courses/base.html' %}
{% load custom_tags %}
{% block title %}
Checkout
{% endblock %}

{% block content %}
<style>
    .card-body {
        padding: 10px;
        height: 150px;
        display: flex;
        flex-direction: column;
        justify-content: space-between;
    }

    .card-title {
        font-size: 20px;
        text-align: center;
    }

    .card {
        width: 18rem;
        margin-bottom: 10px;
        border-radius: 0;
    }

    .card-text {
        font-size: 20px;
        text-align: center;
        margin-top: 5px;
    }

    .card-footer {
        display: flex;
        justify-content: space-between;
        border: none;
        margin: 0;
    }

    .card-footer .col {
        border: none;
        padding: 0;
        margin: 0;
    }

    .card-footer a {
        display: block;
        padding: 5px 10px;
        text-align: center;
        text-decoration: none;
        border: 1px solid gray;
    }

    .checkout-wrapper {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-top: 50px;
    }

    .checkout-details {
        text-align: center;
    }

    .checkout-details p {
        font-size: 24px;
        margin-bottom: 20px;
    }

    .checkout-details p.course-title {
        font-size: 32px;
        font-weight: bold;
        margin-bottom: 10px;
        color: #333;
    }

    .checkout-details p.payable-amount {
        font-size: 28px;
        margin-bottom: 10px;
        color: #555;
    }

    .checkout-details p.payable-amount b {
        font-weight: bold;
        color: #222;
    }

    .checkout-details a {
        display: inline-block;
        padding: 10px 20px;
        font-size: 20px;
        text-decoration: none;
        border: 1px solid gray;
        background-color: #f8f9fa;
        color: #333;
        transition: background-color 0.3s ease;
    }

    .checkout-details a:hover {
        background-color: #e9ecef;
    }
</style>
<div class="container">
    <br>
    <hr>
    <div class="row checkout-wrapper">
        <div class="col mx-auto">
            <div class="card mx-auto" style="width: 35rem;">
                <img src="https://dz8fbjd9gwp2s.cloudfront.net/courses/63b87ffee4b0b82420c664f3/63b87ffee4b0b82420c664f3_scaled_cover.jpg?v=1"
                    class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title text-center">{{course.title}}</h5>
                    <p class="card-text m-0 p-0">
                        save {{course.discount}}%
                        <br>
                        <span class="price">
                            <del>{{course.price|rupee}}</del>
                            &nbsp;
                            <span>{% cal_sale_price course.price course.discount as amount %} {{amount|rupee}}</span>
                        </span>
                    </p>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="checkout-details">
                <p class="display-4 text-center course-title">{{course.title}}</p>
                <hr>
                <p class="display-4 text-center payable-amount">Payable Amount: <b>{% cal_sale_price course.price course.discount as amount %} {{amount|rupee}}</b></p>
                <a class="btn btn-light border" href="?action=create_payment" style="background-color: skyblue; color: #333;">Continue to payment</a>
            </div>
        </div>
    </div>
</div>
{% if order is not None%}
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script>
    var options = {
        "key": "rzp_test_XHFjYcFZZafZcJ", // Enter the Key ID generated from the Dashboard
        "name": "RKMVCC", //
        "description": "Payment for {{course.title}}",
        "image": "https://example.com/your_logo",
        "order_id": "{{order.id}}", //This is a sample Order ID. Pass the `id` obtained in the response of Step 1
        "callback_url": "http://127.0.0.1:8000/verify_payment",
        "prefill": {
            "name": "{{user.first_name}}",
            "email": "{{user.email}}",
        },
        "theme": {
            "color": "#3399cc"
        }
    };
    var rzp1 = new Razorpay(options);
        rzp1.open();
</script>
{% endif %}

{% if error is not None %}
<script>
    window.onload=()=>{ 
        alert("{{error}}")
    }
    </script>
{% endif %}

{% endblock %}

onlineclasses/templates/courses/contact_us.html
{% extends 'courses/base.html' %}

{% block title %}
Contact Us
{% endblock %}

{% block content %}
<style>
  body {
      font-family: Arial, sans-serif;
      margin: 0;
      padding: 0;
  }

  .container {
      width: 100%;
      height: 100vh;
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
      background-color: #f1f1f1;
  }

  .contact-info {
      background-color: #e1bee7;
      width: 400px;
      padding: 40px;
      border-radius: 10px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
      text-align: center;
  }

  .email {
      font-size: 24px;
      color: #333333;
      margin-bottom: 20px;
  }

  .phone {
      font-size: 24px;
      color: #333333;
  }

  .address{
    font-size: 24px;
    color: #333333;
  }
</style>
    <div class="container">
        <div class="contact-info">
            <h2>Contact Us</h2>
            <p class="email">Email: andrewhu@gmail.com</p>
            <p class="phone">Phone: 7436263835</p>
            <p class= "address">Address: xyz street, kolkata 700000 West Bengal</p>
        </div>
    </div>
</body>
{% endblock %}


onlineclasses/templates/courses/course_page.html
{% extends 'courses/base.html' %}

{% block title %}
course_page
{% endblock %}

{% block content %}
<style>
    .container-fluid {
        margin-top: 50px;
        text-align: center;
    }

    .display-1 {
        font-size: 36px;
        margin-bottom: 20px;
    }
</style>

<div class="container-fluid">
    <h1 class="display-1">Selected Course: {{ course.title }}</h1>
    <h1 class="display-1">Price: {{ course.price }}</h1>
    <h1 class="display-1">Discount: {{ course.discount }}</h1>
    <h1 class="display-1">Description: {{ course.description }}</h1>
</div>
{% endblock %}

onlineclasses/templates/courses/explore_courses.html
{% extends 'courses/base.html' %}
{% load custom_tags %}
{% block title %}
Explore Courses
{% endblock %}
{% block content %}

<style>
    .card-body {
        padding: 10px;
        height: 150px;
        display: flex;
        flex-direction: column;
        justify-content: space-between;
    }

    .card-title {
        font-size: 20px;
        text-align: center;
    }

    .card {
        width: 18rem;
        margin-bottom: 10px;
        border-radius: 0;
    }

    .card-text {
        font-size: 20px;
        text-align: center;
        margin-top: 5px;
    }

    .card-footer {
        display: flex;
        justify-content: space-between;
        border: none;
        margin: 0;
    }

    .card-footer .col {
        border: none;
        padding: 0;
        margin: 0;
    }

    .card-footer a {
        display: block;
        padding: 5px 10px;
        text-align: center;
        text-decoration: none;
        border: 1px solid gray;
    }

    .btn-enroll-now,
    .btn-show-more {
        font-size: 15px;
        margin-top: 5px;
    }
</style>
<div class="container-fluid">
    <br>
    <div class="row">
        {% for item in courses %}
        <div class="col-md-6 col-lg-4 mb-4">
            <div class="card mx-auto" style="width: 18rem;">
                <img src="https://dz8fbjd9gwp2s.cloudfront.net/courses/63b87ffee4b0b82420c664f3/63b87ffee4b0b82420c664f3_scaled_cover.jpg?v=1"
                    class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title text-center">{{item.title}}</h5>
                    <p class="card-text m-0 p-0">
                        save {{item.discount}}%
                        <br>
                        <span class="price">
                            <del>{{item.price|rupee}}</del>
                            &nbsp;
                            <span>{% cal_sale_price item.price item.discount as amount %} {{amount|rupee}}</span>
                        </span>
                    </p>
                </div>
                <div class="card-footer">
                    {% is_enrolled request item as enrolled %}
                    <div class="row no-gutters">
                        {% if enrolled %}
                        <div class="col d-flex justify-content-center">
                            <a class="btn btn-block btn-enroll-now" href="/">Start Course</a>
                        </div>
                        {% else %}
                        <div class="col d-flex justify-content-center">
                            <a class="btn btn-block btn-enroll-now" href="/checkout/{{ item.slug }}">Enroll Now</a>
                        </div>
                        {% endif %}
                    </div>
                    <div class="row no-gutters">
                        <div class="col d-flex justify-content-center">
                            <a class="btn btn-block btn-show-more" href="/courses/{{ item.slug }}">Show More</a>
                        </div>

                    </div>

                </div>

            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

onlineclasses/templates/courses/home.html
{% extends 'courses/base.html' %}
{% block title %}
Home page
{% endblock %}

{% block content %}

<style>
    body {
        font-family: Arial, sans-serif;
        margin: 0;
        padding: 0;
        background-color: darkgray;
    }

    .btn-explore {
        background-color: #4CAF50;
        color: white;
        padding: 12px 24px;
        font-size: 18px;
        border: none;
        border-radius: 4px;
        text-decoration: none;
    }

    .btn-explore:hover {
        background-color: #45a049;
    }

    .container {
        width: 100%;
        height: 100vh;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        background-color: #E6E6FA;
    }

    h1 {
        font-size: 48px;
        color: blue;
        margin-bottom: 20px;
        text-align: center;
    }

    p {
        font-size: 20px;
        color: black;
        text-align: center;
    }

    .btn {
        display: inline-block;
        padding: 16px 32px; /* Adjust padding values as needed */
        font-size: 24px; /* Adjust font size as needed */
        text-align: center;
        text-decoration: none;
        background-color: orangered; /* Change the background color */
        color: #FFFFFF;
        border-radius: 6px;
        transition: background-color 0.3s;
        margin-right: 10px;
    }

    .btn.yellow:hover {
        background-color: #e6b800;
    }

    .border {
        border: 1px solid #ccc;
        padding: 0px;
    }

</style>
</head>

<span style="font-size: 10px;">{{ request.user }}</span>
<div class="container">
    <h1 class="display-1">Hello There!</h1>
    <p class="intro">Welcome to our amazing collection of courses.Expand your knowledge and enhance your skills with our
        comprehensive learning materials.</p>
        <div class = "btn-container">
        <a class="btn" href="/explore_courses">Explore Courses</a>
</div>
</div>
{% endblock %}

onlineclasses/templates/courses/password_reset.html
<!-- password_reset_form.html -->

{% block content %}
  <style>
    .container {
      max-width: 400px;
      margin: 0 auto;
      padding: 20px;
      background-color: #f2f2f2;
      border-radius: 5px;
      text-align: center;
      box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
    }

    .title {
      font-size: 24px;
      font-weight: bold;
      margin-bottom: 20px;
    }

    .form {
      text-align: left;
    }

    .form-label {
      font-weight: bold;
    }

    .form-input {
      width: 100%;
      padding: 10px;
      margin-bottom: 15px;
      border-radius: 4px;
      border: 1px solid #ccc;
    }

    .form-submit {
      width: 100%;
      padding: 10px;
      background-color: #4CAF50;
      color: white;
      border: none;
      border-radius: 4px;
      cursor: pointer;
    }
  </style>

  <div class="container">
    <h2 class="title">Password Reset</h2>
    <form class="form" method="post">
      {% csrf_token %}
      <label class="form-label" for="id_email">Email:</label>
      <input class="form-input" type="email" id="id_email" name="email" required>
      <input class="form-submit" type="submit" value="Reset Password">
    </form>
  </div>
{% endblock %}

onlineclasses/templates/courses/password_reset_complete.html
<!-- password_reset_done.html -->


{% block content %}
  <style>
    .container {
      max-width: 600px;
      margin: 0 auto;
      padding: 20px;
      background-color: #f2f2f2;
      border-radius: 5px;
      text-align: center;
    }

    .title {
      font-size: 24px;
      font-weight: bold;
      margin-bottom: 10px;
    }

    .success-message {
      font-size: 16px;
      margin-bottom: 10px;
      color: green;
    }

    .info-message {
      font-size: 16px;
      margin-bottom: 10px;
      color: blue;
    }
  </style>

  <div class="container">
    <h2 class="title">Password Reset Successful</h2>
    <p class="success-message">Your password has been successfully reset.</p>
    <p class="info-message">You can now log in with your new password.</p>
  </div>
  <a href="/login">login</a>
{% endblock %}

onlineclasses/templates/courses/signup.html
{% extends 'courses/base.html' %}

{% block title %}
Signup
{% endblock %}

{% block content %}

<style>
  body {
    background-color:#0000ff82;
    font-family: Arial, sans-serif;
  }

  .container {
  width: 400px;
  margin: 30px auto;
  background-color: #f2f2f2;
  border-radius: 5px;
  padding: 15px;
  text-align: center;
  box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
}
.container label {
  color: #000080; /* Replace with your desired label color */
}


  h2 {
    text-align: center;
    color: #333;
  }

  label {
    display: block;
    margin-top: 10px;
    color: #666;
    font-size: 18px;
  }

  input[type="text"],
  input[type="password"],
  input[type="email"] {
    width: 100%;
    padding: 10px;
    margin-top: 5px;
    margin-bottom: 10px;
    border: 1px solid #ccc;
    border-radius: 3px;
    box-sizing: border-box;
    font-size: 13px;
  }

  input[type="submit"] {
    background-color: #4CAF50;
    color: #fff;
    border: none;
    padding: 15px 30px;
    cursor: pointer;
    border-radius: 3px;
    font-size: 20px;
  }

  input[type="submit"]:hover {
    background-color: #45a049;
  }

  .existing-user {
    text-align: center;
    margin-top: 10px;
  }

  .existing-user a {
    color: #FF0000;
    text-decoration: none;
  }

  .existing-user a:hover {
    text-decoration: underline;
  }

  .homepage-button {
    position: absolute;
    top: 10px;
    left: 10px;
    background-color: #333;
    color: #fff;
    padding: 5px 10px;
    border-radius: 3px;
    text-decoration: none;
  }
  
  h1.display-1 {
    font-size: 30px;
    color: #006400;
    
  }
</style>

<div class="container">
  <h1 class="display-1">Signup Page</h1>
  <div>
    <form action="/signup" method="POST">
      {% csrf_token %}
      <div class="mb-3">
        <label for="id_first_name" class="form-label">First Name:</label>
        {{ form.first_name }}
      </div>
      <div class="mb-3">
        <label for="id_last_name" class="form-label">Last Name:</label>
        {{ form.last_name }}
      </div>
      <div class="mb-3">
        <label for="id_username" class="form-label">Username:</label>
        {{ form.username }}
      </div>
      <div class="mb-3">
        <label for="id_email" class="form-label">Email:</label>
        {{ form.email }}
      </div>
      <div class="mb-3">
        <label for="id_password1" class="form-label">Password:</label>
        {{ form.password1 }}
      </div>
      <div class="mb-3">
        <label for="id_password2" class="form-label">Confirm Password:</label>
        {{ form.password2 }}
      </div>
      <div class="text-center">
        <input type="submit" value="Register" class="btn btn-primary">
      </div>
    </form>
    <div class="existing-user">
      <a href="/login" style="font-size: 18px;">Already have an account? Click here</a>
    </div>
  </div>
</div>
{% endblock %}